### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by johnlreilly** [haseebnqureshi/serverless-hq#29]
I tried to install on SLS 1.3 (Windows OS).  The "install npm" worked fine.  When I run sls-hq and answer the prompts it says "Working on your new Serverless project..." but then nothing happens and no directory is created.  It returns to the command prompt.   Are the CRUD resources (prompt) the objects I want scaffolded e.g. Cars, Boats, Airplanes, Passengers?

**Comment by haseebnqureshi** [comment]
Hey @johnlreilly -- really sorry to hear that. Can you verify which sls-hq version you're using?
